Repository ExploreASL/ExploreASL, pull requests merged in 2020-08, with the labels that each got.

#64 Feature#3 ASL registration using affine/DCT
  CustomScripts/EPAD/xASL_wrp_Reslice_func.m
  CustomScripts/StudySpecificScripts/Craniosynostosis/createAverageCBF.m
  DataParTemplate.m
  Functions/xASL_im_CreatePseudoCBF.m
  Functions/xASL_im_CreateSliceGradient.m
  Functions/xASL_init_FileSystem.m
  Functions/xASL_spm_affine.m
  Modules/SubModule_ASL/xASL_wrp_CreateAnalysisMask.m
  Modules/SubModule_ASL/xASL_wrp_ProcessM0.m
  Modules/SubModule_ASL/xASL_wrp_RegisterASL.m
  Modules/SubModule_ASL/xASL_wrp_ResampleASL.m
Labels: enhancement

#49 Closes #32 docker integration and #46 compilation error
  Development/ExploreASL_make_standalone/ExploreASL_make_standalone.m
  ExploreASL_ImportConfig.m
  External/mediri/xASL_io_mTRIAL.m
Labels: bug, enhancement

#97 #93 Fixes #93
  Modules/SubModule_Population/xASL_wrp_CreatePopulationTemplates.m
Labels: bug

#100 Bug #99 loading metadata
  Functions/xASL_init_LoadMetadata.m
  Functions/xASL_str2num.m
Labels: bug

#103 #102 Fixes #102
  Modules/SubModule_Population/xASL_wrp_CreatePopulationTemplates.m
Labels: bug

#104 Fixed the results table creation for TestCases
  Development/xASL_qc_TestExploreASL.m
Labels: enhancement
