Repository ExploreASL/ExploreASL, pull requests merged in 2020-12, with the labels that each got.

#240 Closes #190 Feature #190 hammers atlas option
  DataParTemplate.m
  External/AtlasesNonCommercial/HammersCAT12.csv
  External/AtlasesNonCommercial/HammersCAT12.nii
  External/AtlasesNonCommercial/HammersCAT12.txt
  External/AtlasesNonCommercial/HammersCAT12vsDARTELCAT12.pdf
  External/README_SPM.txt
  External/SPMmodified/toolbox/cat12/cat_main.m
  External/SPMmodified/toolbox/cat12/cat_main_roi.m
  Modules/SubModule_Structural/xASL_wrp_SegmentT1w.m
Labels: Feature

#249 Bug #248 native space
  Functions/xASL_init_FileSystem.m
  Modules/SubModule_Population/xASL_im_CreateAnalysisMask.m
Labels: bug

#242 Closes #241 Add warning when chosen loading data without x structure output
  ExploreASL.m
  ExploreASL_Initialize.m
  ExploreASL_Master.m
Labels: Feature

#237 Close #191 xASL_stat_GetVolumeStatistics: remove FLAIR warning
  Functions/xASL_adm_MakeStandalone.m
  Modules/SubModule_Population/xASL_stat_GetVolumeStatistics.m
  README.md
Labels: bug

#188 Feature #20 basil implementation
  DataParTemplate.m
  Functions/xASL_adm_CreateFileReport.m
  Functions/xASL_adm_LoadParms.m
  Functions/xASL_im_MaskNegativeVascularSignal.m
  Functions/xASL_im_MaskPeakVascularSignal.m
  Functions/xASL_im_PreSmooth.m
  Functions/xASL_im_Upsample.m
  Functions/xASL_init_FileSystem.m
  Functions/xASL_qc_CreatePDF.m
  Modules/SubModule_ASL/xASL_wrp_CreateAnalysisMask.m
  Modules/SubModule_ASL/xASL_wrp_Quantify.m
  Modules/SubModule_ASL/xASL_wrp_ResampleASL.m
  Modules/SubModule_ASL/xASL_wrp_VisualQC_ASL.m
  Modules/xASL_module_ASL.m
Labels: Feature

#233 Feature #35 b sup calculation
  CustomScripts/EPAD/DataParsOther/ASLQParms.json
  CustomScripts/EPAD/DataParsOther/ASLQParmsMissing.json
  CustomScripts/EPAD/DataParsOther/DATA_PAR_Philips2DEPI_Bsup_020_022_030_040.m
  CustomScripts/EPAD/DataParsOther/DATA_PAR_Philips2DEPI_Bsup_040_Only.m
  CustomScripts/EPAD/DataParsOther/DATA_PAR_Philips2DEPI_Bsup_050_DifferentSettings.m
  CustomScripts/EPAD/DataParsOther/DATA_PAR_SI_PASL_2DEPI noBsup_012_031.m
  CustomScripts/EPAD/DataParsOther/DATA_PAR_SI_PASL_3DGRASE_Bsup_010_011_060.m
  CustomScripts/EPAD/DataParsOther/DataPar_GE3Dspiral.m
  CustomScripts/EPAD/EPAD_ASL_parmsPrepare.m
  CustomScripts/EPAD/EPAD_CreateASL_ParsOverview.m
  CustomScripts/StudySpecificScripts/BSup/regroupScans.m
  CustomScripts/StudySpecificScripts/BSup/regroupScripts.m
  CustomScripts/StudySpecificScripts/BioFinder/Structurizing_Import.m
  CustomScripts/StudySpecificScripts/CRUISE_OLD/DATA_PAR_explore_asl_LV.m
  CustomScripts/StudySpecificScripts/CRUISE_OLD/average_quantify_ASL_LV.m
  CustomScripts/StudySpecificScripts/RADAR/DataPar.m
  DataParTemplate.json
  DataParTemplate.m
  Development/BIDS/load2bids.m
  Development/BScalculation.m
  External/ExploreASL_GUI/ExploreASL_GUI/xASL_GUI_Parms.py
  External/TestDataSet/analysis/Sub-001/ASL_1/ASL4D.json
  External/TestDataSet/analysis/Sub-001/ASL_1/M0.json
  External/mediri/xASL_io_mTRIAL.m
  Functions/xASL_adm_GetPhilipsScaling.m
  Functions/xASL_adm_LoadParms.m
  Functions/xASL_bids_parms2BIDS.m
  Functions/xASL_import_json.m
  Functions/xASL_quant_BSupCalculation.m
  Functions/xASL_quant_M0.m
  Modules/SubModule_ASL/xASL_wrp_ProcessM0.m
  Modules/SubModule_ASL/xASL_wrp_Quantify.m
  Modules/xASL_module_ASL.m
Labels: Feature

#230 Feature #223 phoenix protocol reader
  Functions/xASL_bids_GetPhoenixProtocol.m
  Functions/xASL_bids_PhoenixProtocolAnalyzer.m
  Functions/xASL_bids_PhoenixProtocolReader.m
Labels: BIDS, Feature
