Repository ExploreASL/ExploreASL, pull requests merged in 2020-09, with the labels that each got.

#108 Feature #96 x asl to bids conversion
  External/TestDataSet/Sub-001/ASL_1/ASL4D.json
  External/TestDataSet/Sub-001/ASL_1/M0.json
  Functions/xASL_bids_parms2BIDS.m
  Functions/xASL_im_MaskPeakVascularSignal.m
  Functions/xASL_qc_CollectQC_ASL.m
  Functions/xASL_stat_ComputeMean.m
Labels: bug

#154 Closes #145 x asl spm deformations zipping functionality
  Functions/xASL_spm_deformations.m
Labels: bug

#150 Feature #148 fixing t1 flair lists
  Development/SaraElgayar_BIDS/xASL_module_Structural_SE.m
  Functions/README.md
  Functions/xASL_vis_VisualizeROIs.m
  Modules/SubModule_Structural/xASL_wrp_VisualQC_Structural.m
Labels: bug

#152 Bug #151 minor bugfixes
  External/SPMmodified/xASL/xASL_exist.m
  External/SPMmodified/xASL/xASL_io_SaveNifti.m
  Functions/xASL_adm_CleanUpBeforeRerun.m
  Functions/xASL_bids_Add2ParticipantsTSV.m
  Functions/xASL_fsl_TopUp.m
  Modules/xASL_module_ASL.m
Labels: Minor improvements, bug

#158 #123 CreateMissingFLAIRStatus
  Modules/xASL_module_Structural.m
Labels: Minor improvements

#160 Closes #159 Use consistent notation
  Development/StatsAnalysis/SPM_VBA_Stats/xASL_wrp_spm_GLM.m
Labels: bug

#161 Bug #143 masks missing
  External/SPMmodified/xASL/xASL_adm_GetFileList.m
  Functions/xASL_vis_Imwrite.m
  Modules/SubModule_Population/xASL_im_CreateAnalysisMask.m
  Modules/xASL_module_Population.m
Labels: bug
