Repository ExploreASL/ExploreASL, pull requests merged in 2020-07, with the labels that each got.

#18 Fix registration bug & report TC instead of sCoV
  Modules/SubModule_ASL/xASL_wrp_RegisterASL.m
Labels: bug

#21 #19 Revamp quantification scripts
  Functions/xASL_quant_AgeSex2Hct.m
  Functions/xASL_quant_FEAST.m
  Functions/xASL_quant_M0.m
Labels: documentation

#29 #28 Fix the issue with loading Lesion masks into CAT.
  CHANGES.md
  External/README_SPM.txt
  External/SPMmodified/toolbox/cat12/cat_run_job.m
  VERSION_1.1.1
  VERSION_1.1.2
Labels: bug

#31 #30 Minor fix the import input parameter for using DCMTK
  CHANGES.md
  ExploreASL_Import.m
  Functions/xASL_bids_Dicom2JSON.m
  VERSION_1.1.3
Labels: bug

#33 #32Suggested Fix Import Michael
  ExploreASL_Import.m
Labels: enhancement

#40 Update xASL_adm_GzipNifti.m
  External/SPMmodified/xASL/xASL_adm_GzipNifti.m
Labels: bug

#51 #48 xASL_io_Nifti2Im.m detect wrong scaling
  External/SPMmodified/xASL/xASL_io_Nifti2Im.m
Labels: enhancement
