Repository ExploreASL/ExploreASL, pull requests merged in 2021-03, with the labels that each got.

#381 Closes #380 ExploreASL_Master: Fix conversion bug
  ExploreASL_Master.m
Labels: bug

#414 Closes #368 spm_jsonwrite: Remove digits for integers
  .gitignore
  External/SPMmodified/spm_jsonwrite.m
  Functions/xASL_num2str.m
Labels: bug

#422 #421 Automatic import scan order in GE
  ExploreASL_ImportBIDS.m
  Functions/xASL_bids_MergeNifti.m
Labels: BIDS, Feature

#434 Close #352 Improve Log Parsing
  Functions/xASL_test_GetLogContent.m
Labels: Feature

#388 Closes #387: xASL_im_ResampleLinearFair: Waitbar bug
  Functions/xASL_im_ResampleLinearFair.m
Labels: Minor improvements, bug

#425 Closes #424 Phoenix Reader and Analyzer fix
  Functions/xASL_bids_PhoenixProtocolAnalyzer.m
  Functions/xASL_bids_PhoenixProtocolReader.m
Labels: bug

#441 #383 Added custom paths to Flavors test script
  Development/BIDS/BIDS_fullPipelineTest.m
Labels: Testing

#448 #403 changes x.M0_usesASLtiming explanation fix
  Functions/xASL_quant_M0.m
Labels: documentation

#446 #415 xASL_Copy: Allow recursive copying of folders
  External/SPMmodified/xASL/xASL_Copy.m
Labels: Feature
