Repository ExploreASL/ExploreASL, pull requests merged in 2021-12, with the labels that each got.

#961 Closes #947 Update finish import script
  ExploreASL_ImportMaster.m
  Modules/SubModule_Import/xASL_imp_CompleteBIDS2Legacy.m
Labels: optimization

#955 Closes #940 Check folder hierarchy
  Modules/SubModule_Import/xASL_imp_ReadSourceData.m
Labels: import

#966 Closes #873 Avoid double ASL4D registration
  Modules/SubModule_Structural/xASL_wrp_LinearReg_T1w2MNI.m
Labels: bug

#981 Closes #975 Fix GE eASL import
  Functions/xASL_bids_BIDSifyASLJSON.m
Labels: import

#994 Closes #993 Update GitHub templates
  .github/ISSUE_TEMPLATE/template_bug.md
  .github/ISSUE_TEMPLATE/template_feature.md
Labels: documentation

#1005 Closes #1003 README redesign
  README.md
Labels: documentation
