Repository ExploreASL/ExploreASL, pull requests merged in 2021-07, with the labels that each got.

#671 #187 xASL_io_Nifti2Im: Load as uint8 int16 or single
  External/SPMmodified/xASL/xASL_io_Nifti2Im.m
Labels: Optimization

#669 Feature #595 x asl io save nifti uint8
  External/SPMmodified/xASL/xASL_io_SaveNifti.m
Labels: feature

#688 #687 ReferenceValues: Update
  Testing/Reference/ReferenceValues.tsv
Labels: Minor improvements

#708 #707 xASL_init_checkDatasetRoot: minor fix derivatives path check
  Functions/xASL_init_checkDatasetRoot.m
Labels: Minor improvements

#693 #692 xASL_fsl_TopUp: Reused variable corrected
  Functions/xASL_fsl_TopUp.m
Labels: bug

#183 #182 WM overlay for QC with contours and template WM.
  DataParTemplate.m
  Modules/SubModule_ASL/xASL_wrp_VisualQC_ASL.m
Labels: feature

#740 #204 ClusterTesting (Tamas)
  Development/ClusterTesting/README.md
  Development/ClusterTesting/check_credentials.py
  Development/ClusterTesting/clear.sh
  Development/ClusterTesting/cluster_commands.sh
  Development/ClusterTesting/define_credentials.py
  Development/ClusterTesting/job_submission.py
  Development/ClusterTesting/modify_credentials.py
  Development/ClusterTesting/remove_credentials.py
  Development/ClusterTesting/requirements.txt
  Development/ClusterTesting/xASL_job_template.run
  Development/ClusterTesting/xASL_test.m
Labels: Testing

#745 #696 Move xASL_adm_GzipAllFiles to ExploreASL_ProcessMaster
  ExploreASL_ProcessMaster.m
  Modules/SubModule_Population/xASL_adm_GzipAllFiles.m
  Modules/xASL_module_Population.m
Labels: Optimization
