Repository ExploreASL/ExploreASL, pull requests merged in 2021-05, with the labels that each got.

#532 Closes #530 ExploreASL_Initialize: Fix population folder bug
  ExploreASL_Initialize.m
Labels: BIDS

#537 Closes #536 xASL_adm_DocInitialize: Copy additional template
  Functions/xASL_adm_DocInitialize.m
Labels: documentation

#540 Closes #535 update bids comparison
  Functions/xASL_bids_CompareStructures.m
Labels: BIDS

#544 Closes #543 x asl num2str auto mode
  Functions/xASL_num2str.m
Labels: bug

#550 Closes #542 ASL context
  Functions/xASL_io_SplitASL.m
Labels: bug

#560 Feature #559 make nifti4 dicom
  DataParTemplate.m
Labels: documentation

#531 Closes #529 TestDataset: Move files, minor initialize update
  ExploreASL_Initialize.m
  External/TestDataSet/README.md
  External/TestDataSet/analysis/DataParameters_HiQ.json
  External/TestDataSet/analysis/DataParameters_LowQ.json
  External/TestDataSet/analysis/README_TestDataSet.txt
  External/TestDataSet/analysis/Sub-001/ASL_1/ASL4D.json
  External/TestDataSet/analysis/Sub-001/ASL_1/M0.json
  External/TestDataSet/analysis/Sub-001/ASL_1/M0.nii.gz
  External/TestDataSet/analysis/Sub-001/FLAIR.json
  External/TestDataSet/analysis/Sub-001/T1.json
  External/TestDataSet/derivatives/ExploreASL/dataPar.json
  External/TestDataSet/derivatives/ExploreASL/dataParLowQuality.json
  External/TestDataSet/derivatives/ExploreASL/sub-001/ASL_1/ASL4D.json
  External/TestDataSet/derivatives/ExploreASL/sub-001/ASL_1/M0.json
  External/TestDataSet/derivatives/ExploreASL/sub-001/ASL_1/M0.nii.gz
  External/TestDataSet/derivatives/ExploreASL/sub-001/FLAIR.json
  External/TestDataSet/derivatives/ExploreASL/sub-001/T1.json
  External/TestDataSet/rawdata/dataset_description.json
  External/TestDataSet/rawdata/sub-Sub1/anat/sub-Sub1_FLAIR.json
  External/TestDataSet/rawdata/sub-Sub1/anat/sub-Sub1_T1w.json
  External/TestDataSet/rawdata/sub-Sub1/perf/sub-Sub1_asl.json
  External/TestDataSet/rawdata/sub-Sub1/perf/sub-Sub1_aslcontext.tsv
  External/TestDataSet/rawdata/sub-Sub1/perf/sub-Sub1_m0scan.json
  External/TestDataSet/rawdata/sub-Sub1/perf/sub-Sub1_m0scan.nii.gz
  External/TestDataSet/sourceStructure.json
  External/TestDataSet/studyPar.json
  Functions/xASL_bids_Config.m
Labels: BIDS

#609 #600 xALS_bids_BIDS2Legacy: Copy participants.tsv if it exists
  Functions/xASL_bids_BIDS2Legacy.m
Labels: BIDS, import

#613 #612 ExploreASL_Initialize: Backwards compatibility (datPar)
  ExploreASL_Initialize.m
Labels: bug
