Repository ExploreASL/ExploreASL, pull requests merged in 2021-02, with the labels that each got.

#258 Feature #163 dicom2 bids
  CustomScripts/StudySpecificScripts/BIDS/BIDSFlavorsTest.m
  CustomScripts/StudySpecificScripts/BIDS/BIDSreorder.m
  Development/BIDS/load2bids.m
  Development/xASL_bids_DataPar2JSON.m
  Development/xASL_bids_TestBidsConversion.m
  ExploreASL_Import.m
  ExploreASL_ImportBIDS.m
  ExploreASL_ImportConfig.m
  External/DCMTK/xASL_mex_DcmtkRead.cpp
  External/DCMTK/xASL_mex_DcmtkRead.mexa64
  External/DCMTK/xASL_mex_DcmtkRead.mexmaci64
  External/DCMTK/xASL_mex_DcmtkRead.mexw64
  External/README_SPM.txt
  External/SPMmodified/spm_dicom_dict.mat
  External/SPMmodified/spm_dicom_dict.txt
  External/SPMmodified/spm_dicom_header.m
  External/SPMmodified/spm_jsonwrite.m
  External/xASL_DICOMLibrary.txt
  Functions/xASL_adm_GetPhilipsScaling.m
  Functions/xASL_adm_Hex2Num.m
  Functions/xASL_bids_CompareStructures.m
  Functions/xASL_bids_Config.m
  Functions/xASL_bids_Dicom2JSON.m
  Functions/xASL_bids_JsonCheck.m
  Functions/xASL_bids_PARREC2JSON.m
  Functions/xASL_bids_Par2JSON.m
  Functions/xASL_bids_PhoenixProtocolAnalyzer.m
  Functions/xASL_bids_VendorFieldCheck.m
  Functions/xASL_bids_parms2BIDS.m
  Functions/xASL_io_DcmtkRead.m
  Functions/xASL_num2str.m
Labels: BIDS

#289 Fix #273 default option gzip nifti
  External/SPMmodified/xASL/xASL_adm_GzipNifti.m
Labels: bug

#293 Bug #291
  Functions/xASL_im_DetermineFlip.m
  Functions/xASL_qc_CollectQC_Structural.m
  Functions/xASL_stat_PrintStats.m
Labels: bug

#284 #283 xASL_stat_GetROIstatistics Improve feedback on missing images
  Functions/xASL_stat_GetROIstatistics.m
Labels: Feature

#301 Closes #300 readme
  README.md
Labels: documentation

#286 #285 ExploreASL: Add x=ans hint
  ExploreASL.m
Labels: Warnings/inputcheck

#303 #302 Remove SPM/LST/CAT12 server calls
  External/README_SPM.txt
  External/SPMmodified/spm_update.m
  External/SPMmodified/toolbox/LST/ps_LST_update.m
  External/SPMmodified/toolbox/cat12/cat12.m
  External/SPMmodified/toolbox/cat12/cat_io_send_to_server.m
  External/SPMmodified/toolbox/cat12/cat_update.m
Labels: Feature

#330 #329 xASL_stat_GetVolumeStatistics: str2num -> xASL_str2num
  Modules/SubModule_Population/xASL_stat_GetVolumeStatistics.m
Labels: bug

#324 #296 added M0-option for looking for Phase Encoding direction
  CustomScripts/EPAD/EPAD_Manage_PEPolar_Parms.m
Labels: Feature

#344 Closes #343
  External/mediri/xASL_io_mTRIAL.m
Labels: Minor improvements

#362 Closes #355
  DataParTemplate.m
Labels: documentation

#370 Closes #369 xASL_test_GetLogContent: unit test
  Testing/UnitTests/xASL_ut_UnitTest_function_GetLogContent.m
  Testing/xASL_ut_UnitTesting.m
Labels: Testing

#377 Closes #376 (Remove files and folders recursively on windows)
  Development/xASL_test_BIDSFlavorsFull.m
Labels: Minor improvements, bug
