Repository ExploreASL/ExploreASL, pull requests merged in 2021-08, with the labels that each got.

#765 Fixes #758 bug in data loading
  Functions/xASL_init_checkDatasetRoot.m
Labels: bug

#764 Fixes #761 xASL_module_ASL: Minor fix for empty images
  Modules/xASL_module_ASL.m
Labels: bug

#771 Fixes #769 Load data bug
  ExploreASL_Initialize.m
Labels: bug

#767 #731 sCoV stats file prints mL/100g/min
  Functions/xASL_stat_PrintStats.m
Labels: bug

#664 Fixes #257 xASL_wrp_CreateBiasfield: Slight revamp
  Modules/SubModule_Population/xASL_wrp_CreateBiasfield.m
Labels: Revamp

#763 Fixes #762 xASL_stat_GetDICOMStatistics: Improve TSV cell array fixing
  Modules/SubModule_Population/xASL_stat_GetDICOMStatistics.m
Labels: bug

#785 Bug #784 m0 type bid simport
  Modules/SubModule_Import/xASL_imp_NII2BIDS_Subject_DefineM0Type.m
Labels: bug

#783 #178 xASL_test_Flavors_DSM2BIDS: Updated new flavors names
  Functions/xASL_test_Flavors_DCM2BIDS.m
Labels: BIDS
