Repository ExploreASL/ExploreASL, pull requests merged in 2021-01, with the labels that each got.

#238 Closes #225: Feature #225 option longitudinal registration
  DataParTemplate.m
  ExploreASL_Master.m
Labels: Feature

#263 Feature #179 cicero
  CHANGES.md
  Functions/xASL_im_ComputeDice.m
  Functions/xASL_im_SplitImageLabels.m
  Functions/xASL_stat_PairwiseDice.m
  Functions/xASL_stat_UniquePairwisePermutations.m
  Functions/xASL_vis_CreateVisualFig.m
  Modules/SubModule_Population/xASL_im_CreateAnalysisMask.m
  Modules/SubModule_Population/xASL_wrp_CreatePopulationTemplates.m
  Modules/xASL_module_Population.m
Labels: Feature

#281 #279 Move documentation, update doc initialize
  CustomScripts/GitHubDocumentation/docs/About.md
  CustomScripts/GitHubDocumentation/docs/Import_Module.md
  CustomScripts/GitHubDocumentation/docs/License.md
  CustomScripts/GitHubDocumentation/docs/Requirements.md
  CustomScripts/GitHubDocumentation/docs/Structural_Module.md
  CustomScripts/GitHubDocumentation/docs/index.md
  CustomScripts/GitHubDocumentation/templates/ABOUT.md
  CustomScripts/GitHubDocumentation/templates/REQUIREMENTS.md
  Development/Documentation_GitHub/ASL_Module.md
  Development/Documentation_GitHub/Functions.md
  Development/Documentation_GitHub/Modules.md
  Development/Documentation_GitHub/Population_Module.md
  Documentation/docs/ASL_Module.md
  Documentation/docs/About.md
  Documentation/docs/Functions.md
  Documentation/docs/Import_Module.md
  Documentation/docs/License.md
  Documentation/docs/Modules.md
  Documentation/docs/Population_Module.md
  Documentation/docs/Requirements.md
  Documentation/docs/SPMxASL.md
  Documentation/docs/Structural_Module.md
  Documentation/docs/Tutorials.md
  Documentation/docs/index.md
  Documentation/templates/ABOUT.md
  Documentation/templates/DATAPAR.md
  Documentation/templates/REQUIREMENTS.md
  Documentation/templates/TUTORIALS.md
  External/SPMmodified/xASL/xASL_adm_ConvertSeconds2TimeString.m
  External/SPMmodified/xASL/xASL_adm_ConvertSlash.m
  External/SPMmodified/xASL/xASL_adm_UnixPath.m
  External/SPMmodified/xASL/xASL_csvWrite.m
  External/SPMmodified/xASL/xASL_im_ConvertMap2Mask.m
  Functions/xASL_adm_DocCrawler.m
  Functions/xASL_adm_DocInitialize.m
Labels: Minor improvements

#287 #282 xASL_module_Population: iWorker>1 error fixed
  Modules/xASL_module_Population.m
Labels: bug
