Repository ExploreASL/ExploreASL, pull requests merged in 2021-04, with the labels that each got.

#461 Bids #266 clean json data par
  DataParTemplate.json
Labels: BIDS

#464 Closes #463 Remove remaining markdown docs
  Functions/README.md
  Modules/README.md
  Modules/SubModule_ASL/README.md
  Modules/SubModule_Population/README.md
  Modules/SubModule_Structural/README.md
Labels: documentation

#453 #452 added atlas descriptions to DataParTemplate
  DataParTemplate.m
  Functions/xASL_init_FileSystem.m
  Functions/xASL_io_ReadDataPar.m
Labels: documentation

#450 Bids #418 slice timing consistency
  Functions/xASL_quant_SliceTiming.m
Labels: BIDS

#482 #454 xASL_qc_TestExploreASL backwards compatibility fix
  Development/xASL_qc_TestExploreASL.m
Labels: bug

#471 #156 xASL_Iteration: include module & subject in error message
  Functions/xASL_Iteration.m
Labels: Minor improvements

#469 Closes #341 Optimization xASL_TrackProgress
  Functions/xASL_im_PVCkernel.m
Labels: Optimization

#488 Feature #457 improving header
  External/SPMmodified/xASL/xASL_adm_GetFileList.m
Labels: documentation

#491 Closes #457 xASL_adm_GetFileList: Improve header
  External/SPMmodified/xASL/xASL_adm_GetFileList.m
Labels: documentation

#500 Closes #499 Minor design change
  Design/ExploreASL_logoHeader.png
  Design/ExploreASL_logoSmall.png
  README.md
Labels: documentation

#516 Closes #515 Documentation update v1.6.0
  Functions/xASL_adm_DocCrawler.m
  Functions/xASL_adm_DocInitialize.m
Labels: documentation

#526 Closes #474 splitting jsons
  Functions/xASL_io_SplitASL.m
Labels: BIDS
