Repository ExploreASL/ExploreASL, pull requests merged in 2021-11, with the labels that each got.

#895 Closes #893 xASL_spm_admin: Allow cell input
  External/SPMmodified/xASL/xASL_spm_admin.m
Labels: bug

#910 Closes #909 xASL_im_M0ErodeSmoothExtrapolate: lower threshold fixed
  Functions/xASL_im_M0ErodeSmoothExtrapolate.m
Labels: bug

#894 Closes #892 ExploreASL_Initialize: rm paths before addpath
  ExploreASL_Initialize.m
Labels: bug

#908 Closes #907 xASL_fsl_SetFSLdir: add WSL2 compatibility
  Functions/xASL_fsl_SetFSLdir.m
Labels: feature

#912 Closes #911 xASL_module_ASL: Revamp initialization
  Modules/xASL_module_ASL.m
Labels: revamp

#934 #932 Remove old import
  Development/Outdated/ExploreASL_Import.m
  Development/Outdated/ExploreASL_ImportConfig.m
Labels: import

#953 #952 xASL_adm_GetDeprecatedFields: Added PVC fields
  Functions/xASL_adm_GetDeprecatedFields.m
Labels: bug
